### ISSUE TITLE
removal of 167.86.73.55

### ISSUE THREAD

**Issue by NeonGamerBot-QK** [STARK-404/INSTA#21]
owned by me, not a proxy.

**Comment by STARK-404** [comment]
167.86.73.55  this ip is redirecting to > 
https://localtunnel.github.io/www/
Is this your website?

**Comment by NeonGamerBot-QK** [comment]
> 167.86.73.55 this ip is redirecting to > [localtunnel.github.io/www](https://localtunnel.github.io/www/) Is this your website?

no thats currently an error,
`*.saahild.com` is with that ip.
the current redirect is an error; i can change it rn if you want proof i own it

**Comment by STARK-404** [comment]
Ok setup the domain i'm removing the list

**Comment by NeonGamerBot-QK** [comment]
if you run dig on: `temp-proof.saahild.com` you should get my servers ip back;

**Comment by STARK-404** [comment]
1st of all didn't took your ip i downloaded from some free proxy list of the tool ..its just a bulk list of proxy not your server...then the all of the ips didn't work from list it will automatically skips if its showing error and i think you didn't have proper knowledge about proxies

**Comment by NeonGamerBot-QK** [comment]
> 1st of all didn't took your ip i downloaded from some free proxy list of the tool ..its just a bulk list of proxy not your server...

ik I can tell
>then the all of the ips didn't work from list it will automatically skips if its showing error and i think you didn't have proper knowledge about proxies

Nope the proxy port was left open for a long time so it got scanned by servers and put up as a free proxy. I later found out and closed the port.

**Comment by NeonGamerBot-QK** [comment]
@STARK-404 still not removed.
