### ISSUE TITLE
brute force 

### ISSUE THREAD

**Issue by Yashw2003** [STARK-404/INSTA#5]
brother how to set up proxy thiss tool working but blocking system proxy after 5 attempts then how to slove still we are trying no results

**Comment by Yashw2003** [comment]
please respond bhaiii
![Screenshot from 2023-10-23 09-15-26](https://github.com/STARK-404/INSTA/assets/148738002/f90840ec-256e-445e-9cc9-53bd9e18c7d4)
![Screenshot from 2023-10-23 09-15-39](https://github.com/STARK-404/INSTA/assets/148738002/456d1d4c-7609-4dda-ad1d-25722a275ea9)

**Comment by STARK-404** [comment]
Yeah bro iam fixing it ! ... it cause of api.. bcoz api will stop after 9 login attempt

**Comment by STARK-404** [comment]
> please respond bhaiii ![Screenshot from 2023-10-23 09-15-26](https://user-images.githubusercontent.com/148738002/277226169-f90840ec-256e-445e-9cc9-53bd9e18c7d4.png) ![Screenshot from 2023-10-23 09-15-39](https://user-images.githubusercontent.com/148738002/277226186-456d1d4c-7609-4dda-ad1d-25722a275ea9.png)

Bro 
```
pip install rich

```

**Comment by Yashw2003** [comment]
Yes brother I install all requirements but blocking proxy after 5 attempts
can we make changes in proxy ip

**Comment by STARK-404** [comment]
Proxy is working well its the error from the Instagram_private_api

**Comment by Yashw2003** [comment]
Ok brother thanks for your valuable reply   and can we hack insta using any
tool that you know

**Comment by Yashw2003** [comment]
Brother right now 30 attempts highest

**Comment by Yashw2003** [comment]
Its not a tool issue it's proxy issue .... We unblocked proxy for
successful attempts

**Comment by STARK-404** [comment]
Can you give me the screenshot or something?

**Comment by Yashw2003** [comment]
@H4CK3R_404 my telegram I'd can you message me in telegram

**Comment by STARK-404** [comment]
Ok

**Comment by Yashw2003** [comment]
Bhai I want to message you please can you contact me in WhatsApp my mobile
number 6300383887

**Comment by Yashw2003** [comment]
@Yashwanthbalu bro my telegram I'd please response

**Comment by STARK-404** [comment]
Ok
