### ISSUE TITLE
Bad data request 

### ISSUE THREAD

**Issue by Raidenhere** [STARK-404/INSTA#6]
When I tried to type passwords it shows that "bad request
 " after typing "dragon" password 
![Screenshot_2023-12-01-07-34-50-16_84d3000e3f4017145260f7618db1d683](https://github.com/STARK-404/INSTA/assets/152574891/d372641e-a837-4b16-a016-c219e8f6d219)

**Comment by STARK-404** [comment]
Proxy issue bro🥲
